# Generated by Django 2.2 on 2019-04-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('toppings', models.CharField(max_length=10)),
                ('sides', models.CharField(max_length=10)),
                ('drink', models.CharField(max_length=10)),
                ('deserts', models.CharField(max_length=10)),
            ],
        ),
    ]
