# Generated by Django 2.2 on 2019-04-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
